spring:
  sleuth:
    sampler:
      probability: 1
  application:
    name: item-service
  rabbitmq:
    host: 192.168.142.135
    port: 5672
    username: admin
    password: admin
    
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#配置访问主机的格式样式 10.8.28.126:item-service:8002 , 10.8.28.126:item-service:8001
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
